1-install_nginx_web_server

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,9 +1,8 @@
 #!/usr/bin/env bash
-
 # install nginx server
 # curl ip/ should return Hello World!
 
-if [ "$EUID" -ne 0 ]
+if [[ $EUID -ne 0 ]]
 then
     echo 'Must be root user' 1>&2
     exit 1
@@ -11,12 +10,20 @@ fi
 
 
 # update your repo and then upgrade
-apt update -y && apt -y upgrade
-
-# install nginx 
-apt install nginx
+if apt-get update -y && apt-get -y upgrade
+then
+    # install nginx
+    apt install nginx
+else
+    echo "Update failed" 1>&2
+    exit 1
+fi
 
 # create an index.html file in /var/www/html
 echo "Hello World!" > /var/www/html/index.html
 
-service nginx restart
+if ! service nginx restart
+then
+    echo "Failed to start Nginx" 1>&2
+    exit 1
+fi
